### ISSUE TITLE
Consul ACL Token Update

### ISSUE THREAD

**Issue by raykao** [terraform-providers/terraform-provider-consul#100]
In addtion to #95 - it would be good if we can update ACL Tokens and Policies that already exisit.

As an example - the Anonymous token - providing it with a new updated ACL Policy that allows it read on all nodes:

```hcl
node_prefix "" {
   policy = "example
}
```

Currently can create a new token and policy but can not update an existing token's policy etc.

**Comment by remilapeyre** [comment]
Hi @raykao, I think making both resource importable should solve your issue. I'm working on the patch to do this.
