### ISSUE TITLE
Meta block on consul_service

### ISSUE THREAD

**Issue by StuporHero** [terraform-providers/terraform-provider-consul#112]
In connection to #101, I'm wondering if there is a technical reason we can't implement a meta block for `consul_service`. I'm trying to register details of my Oracle database system created in OCI that could lose support if I install a consul agent directly on it, so I'm treating it like an external service. I'd like to use the specifics of the database in a provisioning workflow that clones a database and updates the config file on the middleware to contain an entry for the new database. I'd be happy to try my hand at implementing it, but I want to make sure this is something that is both in line with the goals of the project and isn't waiting on something else before I make the time investment.

**Comment by remilapeyre** [comment]
Hi @StuporHero, thanks for opening this issue!

`Meta` is optional and I think nobody needed it until now, adding a `meta` attribute to `consul_service` would be nice. You can try yo implement it and I would be happy to guide you through the process if you need help.

**Comment by StuporHero** [comment]
@remilapeyre Actually, I just reviewed #104, and it looks like that PR adds the `meta` block. Merging that PR should get me what I need. Any idea when that'll be possible? It looks like it was waiting on a release that may have been delayed.

**Comment by remilapeyre** [comment]
Hi @StuporHero, I think you are confusing the `NodeMeta` and `ServiceMeta` attributes. Both can be set when registring a service in Consul (see https://www.consul.io/api/catalog.html#sample-response-3). `NodeMeta` is exposed in `consul_node` but `ServiceMeta` is not present in `consul_service` and there is no way to set it as far as I know.

I think #104 should be merged in a couple of days.

**Comment by StuporHero** [comment]
@remilapeyre You would be correct. I don't know what I saw that made me think #104 would fix my problem.

**Comment by StuporHero** [comment]
@remilapeyre I've got some questions about writing the tests. Is it okay if I go ahead and create a pull request with what I've got so far to make it easier to collaborate on it?

**Comment by remilapeyre** [comment]
Yes absolutely!

**Comment by remilapeyre** [comment]
Thanks @StuporHero for the PR!
