### ISSUE TITLE
error creating ACL policy

### ISSUE THREAD

**Issue by ars05** [terraform-providers/terraform-provider-consul#113]
Trying to populate a policy in Consul using terraform consul_acl_policy resource but I get 404 - I have attached the DEBUG log.

Policy which I'd to populate is valid and tested.

### Terraform Version
Terraform v0.11.14

### Affected Resource(s)
consul_acl_policy
https://www.terraform.io/docs/providers/consul/r/acl_policy.html

### Terraform Configuration Files
```hcl
resource "consul_acl_policy" "test" {
  name        = "my_policy"
  datacenters = ["eu-west-1"]
  rules       = <<RULE
    node_prefix "" {
      policy = "read"
    }
    RULE
}
```

### Debug Output
[TF_LOG.txt](https://github.com/terraform-providers/terraform-provider-consul/files/3202555/TF_LOG.txt)

### Expected Behavior
ACL should have been populated in Consul ACL

### Actual Behavior
```bash
Error: Error applying plan:

1 error occurred:
	* consul_acl_policy.test: 1 error occurred:
	* consul_acl_policy.test: error creating ACL policy: Unexpected response code: 404 ()
```

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Consul version 1.1.0

**Comment by remilapeyre** [comment]
Hi @ars05, the `consul_acl_policy` is part of the new policy system introduced in Consul 1.4.0 so you cannot use it with Consul 1.1.0.
