### ISSUE TITLE
Role resource

### ISSUE THREAD

**Issue by mytototo** [terraform-providers/terraform-provider-consul#123]
Hi,

I'd like to create Consul roles from Terraform, so I can have a complete control of policies, tokens, and roles.

I can't find docs about a role resource.
Am I missing something ? Is this something planned ?

Thanks.

**Comment by remilapeyre** [comment]
Hi @mytototo, does https://www.terraform.io/docs/providers/consul/r/acl_policy.html do what you want?

**Comment by mytototo** [comment]
Hi @remilapeyre, it looks like it doesn't do what I need since it doesn't apply a policy to a role but only creates a policy.

**Comment by remilapeyre** [comment]
Sorry yes, you are right. We don't have a `consul_acl_role` yet

**Comment by mytototo** [comment]
Just out of curiosity, is this something planned in a near future or not ?

**Comment by remilapeyre** [comment]
I just forgot it, I should be able to write a PR for this in the next few days.

**Comment by mytototo** [comment]
This is great news ! Thank you very much.

**Comment by spuder** [comment]
Implemented here: https://github.com/terraform-providers/terraform-provider-consul/issues/139

Just waiting on to 2.6.0 release.
