### ISSUE TITLE
Configurable Behaviour for `consul_key_prefix`

### ISSUE THREAD

**Issue by lawliet89** [terraform-providers/terraform-provider-consul#129]
### Affected Resource(s)

- `consul_key_prefix`

I was thinking of submitting a PR to add additional configurable behaviour for the `consul_key_prefix` resource. Before I do that, i wanted to ask the maintainers to see if this is desireable.

- Currently, `consul_key_prefix` will error if there are existing keys in the prefix. I was thinking of adding a boolean attribute `ignore_existing_keys` or `delete_existing_keys` which defaults to `false` for backward compatibility that will turn this off. If set to `false`, the resource will delete any existing key and take exclusive control of the prefix as the resource is intended to.
- `consul_keys` have `key` blocks that allows `delete` to be set to `false`. I am thinking of adding a similar behaviour to either the `subkey` blocks or top level block to allow configuring of this behaviour. This should probably default to `true` for backward compatibility.

Would this be acceptable to implement for the maintainers?

**Comment by remilapeyre** [comment]
Hi @lawliet89, thanks for opening an issue!

Regarding `delete_existing_keys`, it is already possible to achieve this behavior as you can import `consul_key_prefix` resources:

``` bash
➜ curl \  
    --request PUT \
    --data "foobar" \ 
    http://127.0.0.1:8500/v1/kv/myapp/config/test

true
➜ curl http://127.0.0.1:8500/v1/kv/myapp/config/test
[
    {
        "LockIndex": 0,
        "Key": "myapp/config/test",
        "Flags": 0,
        "Value": "Zm9vYmFy",
        "CreateIndex": 24,
        "ModifyIndex": 24
    }
]
➜ cat example.tf 
resource "consul_key_prefix" "myapp_config" {
  path_prefix = "myapp/config/"

  subkeys = {
    "foo" = "bar"
  }
}
➜ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # consul_key_prefix.myapp_config will be created
  + resource "consul_key_prefix" "myapp_config" {
      + datacenter  = (known after apply)
      + id          = (known after apply)
      + path_prefix = "myapp/config/"
      + subkeys     = {
          + "foo" = "bar"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

➜ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # consul_key_prefix.myapp_config will be created
  + resource "consul_key_prefix" "myapp_config" {
      + datacenter  = (known after apply)
      + id          = (known after apply)
      + path_prefix = "myapp/config/"
      + subkeys     = {
          + "foo" = "bar"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

consul_key_prefix.myapp_config: Creating...

Error: 1 keys already exist under myapp/config/; delete them before managing this prefix with Terraform

  on example.tf line 1, in resource "consul_key_prefix" "myapp_config":
   1: resource "consul_key_prefix" "myapp_config" {


➜ terraform import consul_key_prefix.myapp_config myapp/config/
consul_key_prefix.myapp_config: Importing from ID "myapp/config/"...
consul_key_prefix.myapp_config: Import complete!
  Imported consul_key_prefix
consul_key_prefix.myapp_config: Refreshing state... [id=myapp/config/]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

➜ terraform apply
consul_key_prefix.myapp_config: Refreshing state... [id=myapp/config/]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # consul_key_prefix.myapp_config must be replaced
-/+ resource "consul_key_prefix" "myapp_config" {
      ~ datacenter  = "dc1" -> (known after apply)
      ~ id          = "myapp/config/" -> (known after apply)
      + path_prefix = "myapp/config/" # forces replacement
      ~ subkeys     = {
          + "foo"  = "bar"
          - "test" = "foobar" -> null
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

consul_key_prefix.myapp_config: Destroying... [id=myapp/config/]
consul_key_prefix.myapp_config: Destruction complete after 0s
consul_key_prefix.myapp_config: Creating...
consul_key_prefix.myapp_config: Creation complete after 0s [id=myapp/config/]

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.
➜ curl http://127.0.0.1:8500/v1/kv/myapp/config/test           
➜ curl http://127.0.0.1:8500/v1/kv/myapp/config/foo 
[
    {
        "LockIndex": 0,
        "Key": "myapp/config/foo",
        "Flags": 0,
        "Value": "YmFy",
        "CreateIndex": 30,
        "ModifyIndex": 30
    }
]
```

If you want to `ignore_existing_keys`, it seems to me that the `consul_keys` resource should do exactly this. Let me know if not.

Regarding `delete` I think, though I'm not sure, that it is present in `consul_keys` for backward-compatible reasons, why not keep the keys in your Terraform scenario as long as you need them?

**Comment by lawliet89** [comment]
Thanks for the reply @remilapeyre 

I am currently running Terraform applications through our CI/CD and I would rather be able to perform all these operations through a single `apply` operation.

My use case is this:

- I have an application whose configuration is templated via Consul Template
- When I deploy a new revision of the application via a rolling update mechanism in Nomad/Kubernetes, I would like the previous version of the application to still "see" the old keys in Consul while the newer revision will "see" the new configuration keys
- So for the `older` revision, the keys were terraformed to `app/revision/1`. The new keys would be terraformed to `app/revision/2`. I use some simple arithmetic in Terraform to increment the index and use modulo to "rollback" to `0` after a certain number to prevent infinite number of revisions in Consul.
- I am currently using `consul_keys` to populate the values but I would like to use `consul_key_prefix` instead to take exclusive ownership of the prefix.
- This would require that I can ask the resource to ignore existing keys in the prefix and simply destroy them and to not delete the previous keys when the resource is modified.

I think this can be done currently with `import` and `state rm` but it would be nicer if this can be done "cleanly" with a resource.

**Comment by remilapeyre** [comment]
Hi @lawliet89 this is a really interesting use-case, I'm not sure how I would approach it. If you want to keep the ownership and the history, do you think something like

```hcl
resource "consul_key_prefix" "myapp_config" {
  count = length(var.revisions)

  path_prefix = "app/revision/${count.index}"
  subkeys = var.revision[count.index]
}
```

would work? As long as you keep the resource, the keys will stay and the old one will be removed when you update `var.revision[...]`.

**Comment by lawliet89** [comment]
Thanks for your suggestion.

The issue I see with the approach you suggested is that I would have to keep the various configuration revisions in `var.revisions` which is not ideal. I would rather have one set of configurations only.

**Comment by remilapeyre** [comment]
Hi @lawliet89, as Terraform resources usually don't have configurable behavior like this is not something that we plan to support in the provider.

If you still want to do this, I think you should be able to take a `consul_key_prefix` datasource, merge the result in `subkeys` with your current configuration and give that to a `consul_key_prefix` resource. This way you will only have the current configuration, but Terraform will fetch the current one before writing to avoid deleting it.

By putting those two resources in a module, you should get something pretty self-contained and easy to use.
