### ISSUE TITLE
[doc] The attribute "meta" is not documented in "consul_service" resource

### ISSUE THREAD

**Issue by marimp** [terraform-providers/terraform-provider-consul#131]
# Affected Resource(s)
Please list the resources as a list, for example:
- consul_service

### Expected Behavior
The 'meta' attribute was recently added to the consul_service resource issue #122 but it is not present in the related documentation (service.html.markdown)

Thanks
Regards

**Comment by remilapeyre** [comment]
Thanks for reporting this @marimp !
