### ISSUE TITLE
datasource consul_service does not export attribute "meta"

### ISSUE THREAD

**Issue by marimp** [terraform-providers/terraform-provider-consul#132]
Hi there,

### Affected Data Source
- data_source_consul_service

### Expected Behavior
The attribute "meta" should be exported in the data source "data_source_consul_service":
```
catalogServiceServiceMeta              = "meta"
```
### Actual Behavior
The attribute "meta" was recently added to resource consul_service in issue #122 but it is not implemented in the related datasource.

If you agree I can implement this feature.

Great Thanks
Regards

**Comment by remilapeyre** [comment]
Hi @marimp, this is a nice addition and your commit looks correct. Can you open a new PR with it?

**Comment by randomswdev** [comment]
@remilapeyre I see you have created a pull request for this (and it seems ok to me). Do you have any idea when this change will likely be committe din master? And any idea of when a new version of the provider will be released?

**Comment by remilapeyre** [comment]
Hi @randomswdev, I plan to make a new release in the next days.
