### ISSUE TITLE
query_options are not read

### ISSUE THREAD

**Issue by marimp** [terraform-providers/terraform-provider-consul#134]
Hi there,

### Terraform Version
Terraform v0.12.0

### Affected Resource(s)
consul/data_source_consul_services
consul/data_source_consul_nodes
consul/data_source_consul_service

### Expected Behavior
The query_options should be read correctly

### Actual Behavior
The "query_options" attributes are not read because they are wrongly read.
In particular the method `getQueryOpts` in `query_options.go` tries to read them at first level while they are children of attribute query_options

### Steps to Reproduce
You can change the test data_source_consul_service_test.go and change the token attribute to a dummy value. This attribute is not taken into consideration

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by remilapeyre** [comment]
Thanks 👏
