### ISSUE TITLE
Can a release (2.5.1?) be cut with #137

### ISSUE THREAD

**Issue by jacobfoard** [terraform-providers/terraform-provider-consul#152]
Hi there, I don't have any issues with the provider itself, but last release was in June and there's been a couple PRs.

I'm specifically interested in #137, but I'm sure there's other people interested in some of the other great things that have been added since then.

Anyway I can help in the getting a version out the door, I'd love to contribute some.

**Comment by remilapeyre** [comment]
Hi @jacobfoard, we plan to do a release in the next days, changes to ACL resources and config entries are much awaited for.

> Anyway I can help in the getting a version out the door, I'd love to contribute some.

Thanks so much for this :) . I have a bit of work to do in https://github.com/terraform-providers/terraform-provider-consul/pull/127 but reviewing the other PRs would be helpful !
