### ISSUE TITLE
consul_keys resource updated in-place deletes and recreates unchanged keys, making plans hard to read

### ISSUE THREAD

**Issue by SarahRiley** [terraform-providers/terraform-provider-consul#162]
This is new in terraform 0.12.  In 0.11, consul_keys showed updates of key values on change, and kept both the other parts of that key block, and other key blocks as is, showing no changes to be made.  In terraform 0.12, the plan shows all keys get deleted and re-added, making it difficult to work out precisely what has changed.

### Terraform Version

0.12.13

### Affected Resource(s)
Please list the resources as a list, for example:
- consul_keys

### Terraform Configuration Files

```
  # consul_keys.product_vars will be updated in-place
  ~ resource "consul_keys" "product_vars" {
        datacenter = "dc1"
        id         = "consul"
      ~ var        = {} -> (known after apply)

      ...
      - key {
          - delete = true -> null
          - flags  = 0 -> null
          - path   = "products/xxxx/env_vars/INVITATION_PATH" -> null
          - value  = "/invitation_old" -> null
        }

      + key {
          + delete = true
          + flags  = 0
          + path   = "products/xxxx/env_vars/INVITATION_PATH"
          + value  = "/invitation"
        }

      - key {
          - delete = true -> null
          - flags  = 0 -> null
          - path   = "products/xxx/env_vars/PASSWORD_PATH" -> null
          - value  = "/password" -> null
        }

      + key {
        + delete = true
        + flags  = 0
        + path   = "products/xxx/env_vars/PASSWORD_PATH"
        + value  = "/password"
      }
      ...
    }
```

### Expected Behavior
 - products/xxxx/env_vars/INVITATION_PATH should show an update of the value in the plan (as the value has changed), but not delete and recreate that key.
 - "products/xxx/env_vars/PASSWORD_PATH" should not show an update in the plan

### Actual Behavior
See plan output above, all items are being recreated

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Make a change so that consul_keys gets updated in-place
1. `terraform plan`

**Comment by remilapeyre** [comment]
Hi @SarahRiley, Terraform 0.12 changed the way it compares `null` for missing values and empty strings. #164 should fix that.

**Comment by SarahRiley** [comment]
Thanks!
