### ISSUE TITLE
Adding a License Resource for Consul Enterprise

### ISSUE THREAD

**Issue by tryan225** [terraform-providers/terraform-provider-consul#172]
This is a feature request to add the ability to [update an Consul Enterprise clusters license](https://www.consul.io/api/operator/license.html#updating-the-consul-license) with this provider.

Other use cases could be:
- [resetting the consul license](https://www.consul.io/api/operator/license.html#resetting-the-consul-license)
- [getting the Consul license](https://www.consul.io/api/operator/license.html#getting-the-consul-license)

There is an example of an enterprise-only feature on this list here with `consul_network_segments`:
- GH-46

**Comment by remilapeyre** [comment]
Hi @tryan225, I implemented this in https://github.com/terraform-providers/terraform-provider-consul/pull/173 but I don't have a Consul Enterprise license so I can't test it right now. I will look into how to test this resource now.
