### ISSUE TITLE
Assign ACL token to role

### ISSUE THREAD

**Issue by ltagliamonte-dd** [terraform-providers/terraform-provider-consul#178]
The current consul_acl_token resource doesn't allow to assign a token to a role.

Only policies seems supported https://www.terraform.io/docs/providers/consul/r/acl_token.html

Using the cli is it possible to create a token and assign it to a role:
```
consul acl token create -description "Monitoring token" -role-id dd9-f5f9-9781-9acc-1fac1527e911
```

Are there any plan to add this? or any workaround?

**Comment by remilapeyre** [comment]
Hi @ltagliamonte-dd, thanks for the remainder, we forgot it when adding `consul_acl_token`.

I just opened a PR with it.
