### ISSUE TITLE
consul_key_prefix resource errors when it does not find key_prefix found in state

### ISSUE THREAD

**Issue by matelang** [terraform-providers/terraform-provider-consul#18]
### Terraform Version
0.9.11.

### Affected Resource(s)
- consul_key_prefix

### Terraform Configuration Files
```
resource "consul_key_prefix" "micro_service" {

  path_prefix = "config/micro-service/"

  subkeys = {
    "database/url"      = "${var.database_host}:3306/${mysql_database.app.name}"
    "database/password" = "${var.root_database_password}"
    // ...
  }
}
```

### Expected Behavior
When deleting a consul cluster and starting a new one from scratch, I expect Terraform to be able to re-provision all our microservice's (Spring Boot & Cloud) configurations based on the consul_key_prefix resource.
This way I could keep all my configuration of the microservices versioned in Git, along with the other deployment aspects (S3 configuration, Route53, Load balancing, ECS, ...).

### Actual Behavior
```
Error refreshing state: 1 error(s) occurred:
* consul_key_prefix.micro_service: consul_key_prefix.micro_service: Failed to list Consul keys under prefix 'config/micro-service/': Unexpected response code: 500
```
It seems that terraform compares the state against the information (not) found in Consul, and in the case that it did not find the expected data there it does not try to re-insert them into the cluster, but rather errors.

### Steps to Reproduce
1) Standard `terraform apply` to a fresh (empty) Consul cluster (we use 3 nodes in HA config).
2) Kill and purge consul cluster so that data is lost.
3) Re-run the previous terrraform apply, expecting that terraform restores the state in consul.
4) See terraform error.

I think this resource should rather do an "upsert" (Insert or Update) like opration instead of failing when it does not find anything.

**Comment by matelang** [comment]
It seems that the problem was not related to the provider. Don't mind this issue.

**Comment by palmertime** [comment]
@matelang I'm am having the same problem.  If you remember the solution, can you share it?

**Comment by matelang** [comment]
Hi @palmertime ,

Unfortunately I don't remember what the solution was, I should have posted it here originally.

In retrospective, I think you could do terraform state rm '<X>' for all the resources that you'd like inserted back, but it's kind of a hackish solution.
