### ISSUE TITLE
consul_config_entry: Unexpected response code: 400

### ISSUE THREAD

**Issue by Crizstian** [terraform-providers/terraform-provider-consul#191]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.12.23
+ provider.consul v2.7.0
+ provider.null v2.1.2
+ provider.vault v2.10.0

Your version of Terraform is out of date! The latest version
is 0.12.24. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)
Please list the resources as a list, for example:
- consul_config_entry

### Terraform Configuration Files
```hcl
resource "consul_config_entry" "service-defaults" {
  count = length(var.app_config_services) > 0 ? length(var.app_config_services) : 0
  
  name = var.app_config_services[count.index].name
  kind = "service-defaults"

  config_json = jsonencode({
    Protocol    = "http"
    MeshGateway = {
      mode = var.app_config_services[count.index].mesh_resolver
    }
  })
}


resource "consul_config_entry" "web" {
  name = "web"
  kind = "service-defaults"

  config_json = jsonencode({
    Protocol    = "http"
  })
}
```

### Debug Output
```bash
Error: Failed to set 'booking-service' config entry: &errors.errorString{s:"Unexpected response code: 400 (Bad request: Request decoding failed: 1 error occurred:\n\t* invalid config key \"Expose\"\n\n)"}

  on ../../consul/central-config/service-defaults/main.tf line 20, in resource "consul_config_entry" "service-defaults":
  20: resource "consul_config_entry" "service-defaults" {



Error: Failed to set 'payment-api' config entry: &errors.errorString{s:"Unexpected response code: 400 (Bad request: Request decoding failed: 1 error occurred:\n\t* invalid config key \"Expose\"\n\n)"}

  on ../../consul/central-config/service-defaults/main.tf line 20, in resource "consul_config_entry" "service-defaults":
  20: resource "consul_config_entry" "service-defaults" {



Error: Failed to set 'notification-api' config entry: &errors.errorString{s:"Unexpected response code: 400 (Bad request: Request decoding failed: 1 error occurred:\n\t* invalid config key \"Expose\"\n\n)"}

  on ../../consul/central-config/service-defaults/main.tf line 20, in resource "consul_config_entry" "service-defaults":
  20: resource "consul_config_entry" "service-defaults" {

Error: Failed to set 'web' config entry: &errors.errorString{s:"Unexpected response code: 400 (Bad request: Request decoding failed: 1 error occurred:\n\t* invalid config key \"Expose\"\n\n)"}

  on ../../consul/central-config/service-defaults/main.tf line 20, in resource "consul_config_entry" "web":
  20: resource "consul_config_entry" "web" {
```

### Expected Behavior
What should have happened?
apply the corresponding configurations

### Actual Behavior
What actually happened?

Unexpected response code: 400 (Bad request: Request decoding failed: 1 error occurred:\n\t* invalid config key \"Expose\"\n\n)"

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by remilapeyre** [comment]
Hi @Crizstian, thanks for opening a bug report! I tried to reproduce the issue but could not. Here's the configuration I used:

```hcl
locals {
  app_config_services = [
    {
      name = "foo"
      mesh_resolver = "local"
    }
  ]
}

resource "consul_config_entry" "service-defaults" {
  count = length(local.app_config_services) > 0 ? length(local.app_config_services) : 0

  name = local.app_config_services[count.index].name
  kind = "service-defaults"

  config_json = jsonencode({
    Protocol    = "http"
    MeshGateway = {
      mode = local.app_config_services[count.index].mesh_resolver
    }
  })
}


resource "consul_config_entry" "web" {
  name = "web"
  kind = "service-defaults"

  config_json = jsonencode({
    Protocol    = "http"
  })
}
```

Your configuration is not complete, can you post a complete example?

Also, what is your Consul version?

**Comment by Crizstian** [comment]
thanks for quick response @remilapeyre 

but this is my full config for service-defaults
```hcl
variable "enable_service_defaults" {
  default = false
}
variable "app_config_services" {
  default = []
}

resource "consul_config_entry" "service-defaults" {
  count = var.enable_service_defaults && length(var.app_config_services) > 0 ? length(var.app_config_services) : 0
  
  name = var.app_config_services[count.index].name
  kind = "service-defaults"

  config_json = jsonencode({
    Protocol    = "http"
    MeshGateway = {
      mode = var.app_config_services[count.index].mesh_resolver
    }
  })
}
```

but if you want to take a look at the whole implementation you can see it here: https://github.com/Crizstian/cinema-microservice-in-GO/blob/step12-multi-vm-cluster/deploy/hashicorp/provision/terraform/tf_cluster/primary/main.tf

and this is my consul version:
Consul v1.6.1

**Comment by remilapeyre** [comment]
Thanks, just tested it and the issue is that we are sending the `Expose` field which is in the `service-defaults` configuration entry in 1.7.

The provider is only tested with the latest version of Consul, from the README:
> This provider targets the latest version of Consul, but older versions should be compatible where possible.

Here the field is sent by the Consul SDK so there is not much we can do. If possible you should upgrade Consul to 1.7.2 and the issue will disappear.

**Comment by Crizstian** [comment]
tested with Consul 1.7.2 and it works properly, the weird thing is that other config entry types works properly with Consul 1.6.1 the only one is service-defaults, but this got fixed with the latest consul version.

Thanks
