### ISSUE TITLE
consul_prepared_query doesn't support NodeMeta or ServiceMeta fields

### ISSUE THREAD

**Issue by cbroglie** [terraform-providers/terraform-provider-consul#192]
Hi there,

### Terraform Version
```
➜  tf git:(master) ✗ terraform -v
Terraform v0.12.24
+ provider.consul v2.7.0
➜  tf git:(master) ✗
```

### Affected Resource(s)
- consul_prepared_query

### Expected Behavior
Consul allows prepared query templates to match using `NodeMeta` and `ServiceMeta` fields, but the Terraform resource isn't aware of them. See https://godoc.org/github.com/hashicorp/consul/api#ServiceQuery. 

### Actual Behavior
The Terraform resource is [unaware of these fields](https://github.com/terraform-providers/terraform-provider-consul/blob/e91a5cce1d71b10cc8b0edd9542a917c88f2f092/consul/resource_consul_prepared_query.go#L280), and therefore cannot read or write them.

### Important Factoids
Most users can probably work around this by using Tags.

**Comment by remilapeyre** [comment]
Hi @cbroglie, thanks for bringing that to my attention :)

https://github.com/terraform-providers/terraform-provider-consul/pull/193 should add the missing attributes you are looking for.

**Comment by cbroglie** [comment]
Thanks!
