### ISSUE TITLE
Add support for Ingress Gateway config entries

### ISSUE THREAD

**Issue by woz5999** [terraform-providers/terraform-provider-consul#199]
### Terraform Version
All versions

### Affected Resource(s)
- consul_config_entry

### Terraform Configuration Files
```hcl
resource "consul_config_entry" "default" {
  kind = "ingress-gateway"
  name = var.ingress_gateway_service_name

  config_json = jsonencode({
     Listeners = [
      {
        Port     = var.por
        Protocol = var.protocol
        Services = var.services
      }
    ]
  })
}
```

### Expected Behavior
No errors

### Actual Behavior
```
Error: Failed to decode config entry: invalid config entry kind: ingress-gateway
```

### Important Factoids
The specific error messages seems to be coming from the vendored hashicorp/consul api package. The current package has support for this config entry type, so I believe the provider just needs an update/build/release to resolve this issue.

[config_entry.go](https://github.com/hashicorp/consul/blob/master/api/config_entry.go#L157-L162)

**Comment by remilapeyre** [comment]
Hi @woz5999, Ingress Gateway are a new feature of Consul 1.8 that just got released. I'm still working on the integration of those features in the Terraform provider but I hope to be able to make a new release shortly :)
