### ISSUE TITLE
Documentation: "certificate_authority" should be "consul_certificate_authority"

### ISSUE THREAD

**Issue by rejackson73** [terraform-providers/terraform-provider-consul#211]
The documentation for the certificate authority (https://www.terraform.io/docs/providers/consul/r/certificate_authority.html) identifies the provider name as "certificate_authority".  When you attempt to provision a resource with name "certificate_authority," the following error message appears:
```
Provider "certificate" not available for installation.

A provider named "certificate" could not be found in the Terraform Registry.
```

The proper name for the resources is "consul_certificate_authority".

**Comment by remilapeyre** [comment]
Hi @rejackson73, thanks for noticing this! We will update the website shortly.
