### ISSUE TITLE
Consul Intentions do not support datacenter argument

### ISSUE THREAD

**Issue by tjrivera** [terraform-providers/terraform-provider-consul#213]
### Terraform Version
Currently running 0.12.18

### Affected Resource(s)
- consul_intention

### Terraform Configuration Files
```hcl
resource "consul_intention" "allow_foo" {
  source_name        = "my-service"
  datacenter            = "dc1"
  destination_name = "my-other-service"
  action                    = "allow"
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
N/A

### Expected Behavior
The [docs for consul_intention](https://www.terraform.io/docs/providers/consul/r/intention.html) state that datacenter should be an optional argument for the resource, but it d 
### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
N/A

### References
Using `consul_node` as an example it looks like the argument is defined [here](https://github.com/terraform-providers/terraform-provider-consul/blob/master/consul/resource_consul_node.go#L24-L29) with fallback to the provider defined datacenter [here](https://github.com/terraform-providers/terraform-provider-consul/blob/master/consul/resource_consul_node.go#L60-L67). It doesn't look like `consul_intention` has this although the docs suggest it should. 

I'd be happy to put a PR together to address this, but wanted to get the issue up first in case I'm missing something important.

**Comment by remilapeyre** [comment]
Hi @tjrivera, I will add this and it should be available in the next release. In the meantime you should be able to set the `datacenter` on the provider definition and it should work.

**Comment by tjrivera** [comment]
Hi @remilapeyre, thanks for the quick reply. It doesn't like this resource goes up the tree to find DC. I have a change in my branch that should do so: https://github.com/tjrivera/terraform-provider-consul/blob/issue213-consul-intentions-dc/consul/resource_consul_intention.go#L75-L83. Just getting approval from my work to make the contribution before submitting a PR :)

**Comment by remilapeyre** [comment]
Thanks for looking into this. Your change looks mostly good, you can just use a call to `getDC()` as it already looks in the resource data if a `datacenter` attribute exists: https://github.com/terraform-providers/terraform-provider-consul/blob/376baf0515e57534cfd7c3cc887323b755464e54/consul/resource_consul_keys.go#L333-L352

Also, I don't think you update `resourceConsulIntentionUpdate()` and the documentation.

**Comment by tjrivera** [comment]
Thanks @remilapeyre, `getDC()` is handy. I've made those changes on my branch. Still waiting for approval from my co to submit a PR. The MPL license is not sanctioned on our side, but we understand that it's used across HashiCorp products, and we'd like to be able to contribute, so we're trying to make it work. 👍
