### ISSUE TITLE
Consul provider fails to refresh state when service removed out-of-band 

### ISSUE THREAD

**Issue by gdavison** [terraform-providers/terraform-provider-consul#23]
When a Consul service is removed out-of-band from the Terraform Consul provider, for instance manually, the provider can no longer refresh its state.

### Terraform-Provider-Consul Version
The provider name in `.terraform/plugins/darwin_amd64/` is `terraform-provider-consul_v0.1.0_x4`

### Affected Resource
- consul_service (I have not verified other resources from the Consul provider)

### Expected Behavior
I should be able to run `plan` or `apply`

### Actual Behavior
Running `plan` or `apply` failed with `Failed to get service 'reqs_redis' from Consul agent`

### Steps to Reproduce
1. Create infrastructure using `terraform apply` which includes service registration with Consul.
2. Manually delete the service or re-create the single `-dev` instance of your Consul cluster.
3. Run `terraform plan` or `terraform apply`
4. See
```
Error refreshing state: 1 error(s) occurred:

* consul_service.redis: 1 error(s) occurred:

* consul_service.redis: consul_service.redis: Failed to get service 'reqs_redis' from Consul agent
```

**Comment by natefaerber** [comment]
@gdavison , is this still valid?  Can you provider TF snippets?  I will try to reproduce but would be good to know I'm using the same config parameters.

**Comment by natefaerber** [comment]
OK, that was easy to reproduce.  I'm going to take a shot at making this work.  Our expectation is that it should just recreate it, right?  I'm not 100% sure a resource provider should behave this way so I'm going to look for other examples that demonstrate a preferred behavior.

**Comment by gdavison** [comment]
Yes, my expectation would be that it would recreate it. For example, if I delete an AWS resource, a `terraform plan` will not fail and a `terraform apply` will recreate the resource.

**Comment by natefaerber** [comment]
👍 My PR (#33) will do this.  Now we need to get the attention of a maintainer.
