### ISSUE TITLE
Provider fails to destroy consul_keys.

### ISSUE THREAD

**Issue by sakaru** [terraform-providers/terraform-provider-consul#35]
### Terraform Version
```bash
$ terraform -v
Terraform v0.11.2
+ provider.consul v1.0.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- consul_keys

### Terraform Configuration Files
```hcl
provider "consul" {
  address = "localhost:8500"
  datacenter = "dc1"
}
resource "consul_keys" "test" {
  key {
    path = "foo"
    value = "bar"
  }
}
```
During the second run it is:
```hcl
provider "consul" {
  address = "localhost:8500"
  datacenter = "dc1"
}
```

### Debug Output
https://gist.github.com/sakaru/e68c9918674bba98428f79ae56ae272d

### Panic Output
n/a

### Expected Behavior
The `consul_keys.test` resource should be destroyed from the consul service.

### Actual Behavior
The resource is not destroyed. Despite what the output says.

### Steps to Reproduce
1. `terraform apply`
2. Remove `consul_keys.test` resource from the `main.tf` file
3. Re-run `terraform apply` (and approve)

### Important Factoids
```
$ consul version
Consul v1.0.2
```
### References
None

**Comment by sakaru** [comment]
Never mind, I didn't see the `delete` argument reference. Closing issue.

**Comment by btyler97** [comment]
Can I ask why an argument is necessary? If I'm running a destroy, I expect all of the resources to be destroyed. I don't understand why you explicitly have to flag them as "delete." Even the plan and destroy output indicate that the resource is going to be and was destroyed respectively.
