### ISSUE TITLE
Recursive Keys

### ISSUE THREAD

**Issue by dblooman** [terraform-providers/terraform-provider-consul#37]
The current data source for consul keys doesn't support using an entire folder, you are required to specify every key.  For my use case, Im versioning config, but want to grab all the key/vales under a folder, for which the keys may have changed.

**Comment by natefaerber** [comment]
I had the same need so I wrote the `consul_key_prefix` data source that was merged into the unreleased 1.1.0.  See https://github.com/terraform-providers/terraform-provider-consul/blob/master/CHANGELOG.md

It should be useful for your needs when it's released.

**Comment by DaveBlooman** [comment]
Excellent, when is the next release? I have written a work around in mean time, but would be good to have this in production

**Comment by natefaerber** [comment]
I don't know when the next release is.  It's a bit slow here.
