### ISSUE TITLE
NodeMeta

### ISSUE THREAD

**Issue by Zeldhyr** [terraform-providers/terraform-provider-consul#40]
Hi,
I need the NodeMeta feature (https://www.consul.io/api/catalog.html#nodemeta).
Will it be implemented soon?
I've done a pull request (#38) for this. What do you think about it?
Thanks for your help

### Terraform Version
0.11.3

**Comment by moserke** [comment]
Thanks for doing this @Zeldhyr!  We needed the same thing and I was just starting to look in to it when I saw this issue.  Hopefully this makes it into the provider soon.

**Comment by pearkes** [comment]
That change in #38 looks good -- just need tests and we can get it merged!
