### ISSUE TITLE
ACL testing that causes a 403 will forever 403 even with the corrected ACL

### ISSUE THREAD

**Issue by vchan2002** [terraform-providers/terraform-provider-consul#44]
### Terraform Version
0.11.5

### Affected Resource(s)
Please list the resources as a list, for example:
"consul_key_prefix"

### Terraform Configuration Files

This is part of the file... but as you see, i'm using a variable for the acl.

```hcl
resource "consul_key_prefix" "myapp_config" {
  token      = "${var.acltoken}"

  # Prefix to add to prepend to all of the subkey names below.
  path_prefix = "${var.kvprefix}"
#Using remote data to get information
  subkeys = "${merge(local.common_poop, var.staticmap)}"
}

```

### Debug Output

This is from terraform

-----------------------------------------------------
2018/04/18 17:54:30 [DEBUG] [aws-sdk-go]
2018/04/18 17:54:31 [INFO] Resource 2018-04-19 00:54:31.347287328 +0000 UTC has dynamic attributes
2018/04/18 17:54:31 [DEBUG] Attaching resource state to "consul_key_prefix.myapp_config": &terraform.ResourceState{Type:"consul_key_prefix", Dependencies:[]string{"local.common_poop"}, Primary:(*terraform.InstanceState)(0xc420733c70), Deposed:[]*terraform.InstanceState{}, Provider:"provider.consul", mu:sync.Mutex{state:0, sema:0x0}}
2018/04/18 17:54:31 [DEBUG] ReferenceTransformer: "consul_key_prefix.myapp_config" references: []
consul_key_prefix.myapp_config: Refreshing state... (ID: devops/poopenvironment/)
2018-04-18T17:54:31.362-0700 [DEBUG] plugin.terraform-provider-consul_v1.0.0_x4: 2018/04/18 17:54:31 [DEBUG] Listing keys under 'devops/poopenvironment/' in us-east-1-staging
2018/04/18 17:54:31 [ERROR] root: eval: *terraform.EvalRefresh, err: consul_key_prefix.myapp_config: Failed to list Consul keys under prefix 'devops/poopenvironment/': Unexpected response code: 403
2018/04/18 17:54:31 [ERROR] root: eval: *terraform.EvalSequence, err: consul_key_prefix.myapp_config: Failed to list Consul keys under prefix 'devops/poopenvironment/': Unexpected response code: 403
2018/04/18 17:54:31 [TRACE] [walkRefresh] Exiting eval tree: consul_key_prefix.myapp_config

This is from consul

    2018/04/19 00:54:31 [ERR] http: Request GET /v1/kv/devops/poopenvironment/?dc=us-east-1-staging&recurse=, error: rpc error making call: ACL not found from=10.7.0.106:57145

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
After I change the variable back to the correct ACL, it should allow the K/V to be setup again.

### Actual Behavior
It keeps 403-ing, complaining of a bad ACL.... 

### Steps to Reproduce
1. `terraform apply with a the right ACL is successful in putting in the K/V'
2.  A change of the ACL variable to a bad ACL, one without the rights.  A terraform plan is OK, but a terraform apply complains to a 403... ONLY IF THERE IS A KEY CHANGE, as it should.  If the change is only the ACL itself, the terraform apply is successful.
3.  Change acltoken back to the correct ACL.
4.  Subsequent plans an applys, even with the right ACL, keeps complaining of the 403.
5.  At this point, I can't plan, apply, refresh, or destroy.  I had go and delete the state file and the k/v and start over.
6.  A subsequent apply works just fine since it had no reference of what's in the past.

### Important Factoids

Looking further into this, it would appear that, when I do a plan and an apply, either way, the bad ACL gets put in the state file.  However, when I put the good ACL back to variable and do a plan, it apparently still tries to use bad ACL to access the K/V, even though I have a good ACL in my variable now, and thus it errors out before it even tries the corrected ACL.  

I was able to verify this by versioning the S3 bucket where the state file is and rolling it back one version, back to where the good ACL is in the state file.  Then a TF plan and apply have no problems.

It would make sense to have some sort of test to see whether the ACL works before putting it in the state file, so that it doesn't get in this "stuck" state?

**Comment by pearkes** [comment]
Thanks for the report @vchan2002. I think this is a challenging aspect to being able to set the token per resource. Terraform is treating it as an attribute and it has a certain lifecycle as a result, something you're witnessing the downside of.

I'm guessing this won't work for you but I doubt you'll see the same issues when setting a single ACL token for the whole provider, described [here](https://www.terraform.io/docs/providers/consul/index.html#token).

**Comment by pearkes** [comment]
It seems like another good and more realistic potential workaround is using [multiple instances of the Consul Provider](https://www.terraform.io/docs/configuration/providers.html#multiple-provider-instances) (with different tokens). I actually think this is better practice overall. However there are some constraints:

- It assumes you don't have 1-1 mappings from `consul_key*` resources to ACL tokens. This would surprise me a bit, but I could see it. Creating new provider instances for every resource if that is your situation would be pretty cumbersome.
- If we ever have an `acl_token` resource, this may not be so great as I believe interpolating into providers has a number of problems.

**Comment by vchan2002** [comment]
@pearkes Thanks for your response.  I'll try moving the token parameter from the resource to the provider and see what happens.
Further down the line, I would probabaly build some sort of pipeline where the token can be planted in a variable so we don't have to hard code the token anywhere.... I don't see that expliclty stated in the documentation as being an option... is that possible at this point?

**Comment by pearkes** [comment]
@vchan2002 Both `CONSUL_TOKEN` and `CONSUL_HTTP_TOKEN` can be specified. I'll update the docs.

https://github.com/terraform-providers/terraform-provider-consul/blob/master/consul/resource_provider.go#L72-L73

**Comment by remilapeyre** [comment]
Now that the documentation references the Consul environment variable and since there has not been any new message on this issue for two years I think we can close it. @vchan2002 Thanks for bringing that up, please reopen the issue if needed.
