### ISSUE TITLE
Add resource to generate consul gossip keys (feature request)

### ISSUE THREAD

**Issue by mildred** [terraform-providers/terraform-provider-consul#48]
It would be great to have somewhere in terraform a resource that would generate a gossip key compatible to the format generated by `consul keygen`. This would help setting up clusters with consul using terraform.

**Comment by Johannestegner** [comment]
I use the following bash command to generate keys for consul: `head -c 16 /dev/urandom | base64 > gossip.txt`, works fine without having to start a consul server to run the keygen command and should be easy enough to "bake" into a terraform resource (or even run through local-exec or something, hehe).

**Comment by remilapeyre** [comment]
@mildred This would be better as a new `random_bytes` resource in the Random terraform provider don't you think?

**Comment by remilapeyre** [comment]
@mildred @Johannestegner I think you will find that `random_id` from the terraform Random provider will do what you need with the b64_std attribute:
```
provider "random" {}

resource "random_id" "gossip_key" {
  byte_length = 16
}
```
the `b64_std` should be what you want:
```
$ terraform state show random_id.server
id          = mo-Y4wH0i9xjU0MA6WhQWQ
b64         = mo-Y4wH0i9xjU0MA6WhQWQ
b64_std     = mo+Y4wH0i9xjU0MA6WhQWQ==
b64_url     = mo-Y4wH0i9xjU0MA6WhQWQ
byte_length = 16
dec         = 205446710713305293954164489563079725145
hex         = 9a8f98e301f48bdc63534300e9685059
``

**Comment by yevgeniyo** [comment]
be aware that nowadays, byte_lenght should be 32

```
provider "random" {}

resource "random_id" "gossip_key" {
  byte_length = 32
}
```
