### ISSUE TITLE
[doc] Argument "datacenter" missing in Argument Reference for consul_node resource

### ISSUE THREAD

**Issue by splashx** [terraform-providers/terraform-provider-consul#56]
### Terraform Version

```
$ terraform version
Terraform v0.11.7
+ provider.consul v2.1.0
```

### Affected Resource(s)

- `consul_node`

### Terraform Configuration Files

* provider.tf

```hcl
provider "consul" {
  datacenter = "dc1"
  scheme = "https"
  address    = "server.example.com"
}
```

* app.tf:
```hcl
resource "consul_node" "app-nodes" {
  name = "some-name"
  address = "100.127.20.51"
}

resource "consul_service" "app-consul-service" {
  name    = "some-service-name"
  node    = "some-name"
  port    = 80
  tags    = ["app"]
  datacenter = "dc1"
  depends_on = ["consul_node.app-nodes"]
}
```

### Expected Behavior

The node resource should have been created.

### Actual Behavior

```
 consul_node.app-nodes: Failed to get datacenter from Consul agent: Unexpected response code: 403 (Permission denied)
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The `Permission Denied` message is correct because the token doesn't have the rights to [`/agent/self`](https://github.com/terraform-providers/terraform-provider-consul/blob/cd61d3e4ef26db08fa383e91b277102f3e61d0aa/consul/resource_consul_keys.go#L335).

However, we wanted to simulate the creation of [External Services](https://www.consul.io/docs/guides/external.html) in consul - which worked via `curl` - via Terraform. We were able to achieve it after explicitly giving the attribute inside the `consul_node` resource block:

```diff
resource "consul_node" "app-nodes" {
  name = "some-name"
  address = "100.127.20.51" 
+  datacenter = "dc1"
}
```
However this is not described in the documentation - we had to pull it out [from the code](https://github.com/terraform-providers/terraform-provider-consul/blob/cd61d3e4ef26db08fa383e91b277102f3e61d0aa/consul/resource_consul_keys.go#L332-L334). It would be good if there would be also the description of the behavior in the documentation.

Since `datacenter` is already defined in the `provider` block, this should have not happened - I'll open another issue because of this.

### References

Documentation page in question: https://www.terraform.io/docs/providers/consul/r/node.html

**Comment by remilapeyre** [comment]
This is indeed a problem, thanks for reporting it.

I opened PR #75 to fix the documentation and will work on #57 in another one.
