### ISSUE TITLE
Enhancement: Add flags support to Consul key management

### ISSUE THREAD

**Issue by delphyne** [terraform-providers/terraform-provider-consul#59]
Preamble: Consul allows you to set an unsigned integer along with a KV that can be used however the provider/consumer wish.  Often, this data contains a bitmask to let consumers know metadata about the key being read (is this value encrypted?, is it json encoded?, is the data binary?).  Terraform current does not support management of the Flags attribute.

### Terraform Version
0.11.7

### Affected Resource(s)
- consul_keys
- consul_key_prefix

### Terraform Configuration Files
proposal for interface changes...
#### consul_keys
because the `consul_keys` resource uses a sub-object, adding a flags attribute is a non-breaking change (with a caveat).  See "expected behavior" below.
```hcl

resource "consul_keys" "app" {
  datacenter = "nyc1"
  token      = "abcd"

  # Set the CNAME of our load balancer as a key
  key {
    path  = "service/app/elb_address"
    value = "${aws_elb.app.dns_name}"
    flags = 64
  }
}
```
#### consul_key_prefix
Consul key prefix uses a map to describe the subkeys, as such, a larger contract change would be necessary.  There are a couple approaches to this, but the most backwards compatible way I can think of is...
```hcl
resource "consul_key_prefix" "myapp_config" {
  datacenter = "nyc1"
  token      = "abcd"

  # Prefix to add to prepend to all of the subkey names below.
  path_prefix = "myapp/config/"

  subkeys = {
    "elb_cname"         = "${aws_elb.app.dns_name}"
    "s3_bucket_name"    = "${aws_s3_bucket.app.bucket}"
    "database/hostname" = "${aws_db_instance.app.address}"
    "database/port"     = "${aws_db_instance.app.port}"
    "database/username" = "${aws_db_instance.app.username}"
    "database/name"     = "${aws_db_instance.app.name}"
  }

  subkey {
    path="database/password"
    value="${aws_db_instance.app.password}"
    flags=64
  }
}
```
it could either be ok to provide both subkeys and [many] subkey elements, or only one or the other could be allowed on any resource.

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Terraform should be able to manage the Flags attributes of a KV, and should ensure that the Flags of a managed KV are always correct.  (See Actual Behavior)

### Actual Behavior
Currently, Terraform ignores flags altogether, so it is possible to use a different tool to write values under a `consul_key_prefix` resource and Terraform will not "put it back".  I'd argue this is a bug, but I imagine people are taking advantage of this (like I am) to overlay flags from another tool, while setting the "content" of the value from Terraform.

If terraform begins to manage flags as well, I also believe that terraform should assume that a key is tainted if the modify index does not match the modify index at the time terraform last set it (but this should probably fixed in a separate PR).

### Steps to Reproduce
N/A

### Important Factoids
N/A

### References
https://www.consul.io/api/kv.html#flags
https://www.consul.io/api/kv.html#flags-1
https://www.consul.io/api/kv.html#modifyindex

**Comment by remilapeyre** [comment]
Hi @delphyne, the attached PR should add what you need for the `consul_keys` resource. I'm not sure about the way to add it to `consul_key_prefix` as adding a new subkey element seems like a major change of this resource to me.

Is there cases where you could not use `consul_keys` to specify the flags?

**Comment by delphyne** [comment]
@remilapeyre i think this solves most of it!  it just doesn't let you manage the keyspace the same way that consul_key_prefix does (removing keys not put there by terraform, etc.).

**Comment by remilapeyre** [comment]
Hi @delphyne , I initially was not a fan of adding `subkey` to `consul_key_prefix` as it introduces a new syntax but looking at it again it seems fine (I still don't completely understand why `consul_key_prefix` work that way though because it seems to be one of the few to remove resources created outside of Terraform).

I will gladly add it amend the PR but would prefer someone from Hashicorp confirm this syntax is ok before developing it.

**Comment by delphyne** [comment]
It maps more like tags on an AWS instance or security group rules. In both cases anything added outside of terraform gets whacked on apply. It is a bit of an anomaly, but also makes sense.

**Comment by remilapeyre** [comment]
You convinced me :) I had not thought of those. The new changeset in #71 does this.
