### ISSUE TITLE
external-source for UI Integration

### ISSUE THREAD

**Issue by pearkes** [terraform-providers/terraform-provider-consul#68]
The Consul UI now respects a special metadata field on services that will show a Terraform icon next to service names if the correct metadata exists on the service.

We should add this to all service registrations performed by the Terraform provider (the `consul_service` resource).

There is more detail here: https://github.com/hashicorp/consul/pull/4640
And an example of it in the k8s catalog sync tool: https://github.com/hashicorp/consul-k8s/blob/ee548ca16e5e3cf94ca8613e4eeba0159ecdc427/catalog/from-k8s/resource.go#L235-L238

**Comment by remilapeyre** [comment]
Hi @pearkes, I opened a new PR to add this information
