### ISSUE TITLE
feature request: support ca path in provider settings

### ISSUE THREAD

**Issue by eedwards-sk** [terraform-providers/terraform-provider-consul#79]
this is a feature request to support the [ca_path](https://www.consul.io/docs/agent/options.html#ca_path) configuration option from consul

currently the only supported provider feature is `ca_file`, which requires a path to a single file

because a valid configuration for consul is to have a directory containing ca files used, I believe that the consul terraform provider should support it, as well

**Comment by remilapeyre** [comment]
Hi @eedwards-sk, thanks for opening a feature request!

This seems reasonable and it is the last TLS configuration attribute missing for the provider.  PR #80 should do what you want.
