### ISSUE TITLE
Consul support for Terraform 0.12?

### ISSUE THREAD

**Issue by igordavid** [terraform-providers/terraform-provider-consul#88]
Hello,

Are there any plans to release Consul provider which will be working with Terraform 0.12, and if so is there any timeline? 

Currently when I try to use newest Terraform 0.12 with Consul, there is an error:

```hcl
./terraform plan

Error: Failed to instantiate provider "consul" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]
```

### Terraform Version
```hcl
./terraform version
Terraform v0.12.0-alpha4 (2c36829d3265661d8edbd5014de8090ea7e2a076)
+ provider.aws v1.40.0-6-gb23683732-dev
+ provider.consul v2.2.0
```

```hcl
consul --version
Consul v1.4.0
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

### Affected Resource(s)
Please list the resources as a list, for example:
- multiple resources

### Terraform Configuration Files
```hcl
data "consul_key_prefix" "common" {
  datacenter = "dc1"
  # Prefix to add to prepend to all of the subkey names below.
  path_prefix = "common/service1"
}

module "alb" {
...
source = "./modules/alb"
CommonAlbRules   = "${data.consul_key_prefix.common.subkeys}"
...

resource "aws_lb_listener_rule" "CommonAlb" {
  count        = "${length("${var.CommonAlbRules}")}"
  ...
}
```

### Expected Behavior
Terraform plan/apply should succeed.

### Actual Behavior
```hcl
Error: Failed to instantiate provider "consul" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Download Terraform 0.12 and Consul 
2. Populate Consul with simple KV
`consul kv put common/service1 service1,8080,http,8080`
4. Configure Consul as a simple Data source
5. `terraform apply`

### References
Possibly this one:
https://github.com/hashicorp/terraform/issues/19221

**Comment by EliaSaSe** [comment]
Hi @remilapeyre 

I'm currently testing terraform 0.12 rc1. But I can't upgrade because this plugin has no 0.12 support for now. What is the progress with the 0.12 compatibility? Will be there an update for this plugin before 0.12 releases?

Best regards,
Elia

**Comment by remilapeyre** [comment]
Hi @EliaSaSe, the work to make this provider work with Terraform 0.12 has been done in the `terraform-0.12` branch (https://github.com/terraform-providers/terraform-provider-consul/tree/terraform-0.12) and it is currently working. The release come shortly.

In the meantime, it is possible to copy the resulting artifact of `make` to the Terraform plugin folder (https://www.terraform.io/docs/configuration/providers.html#third-party-plugins) and you should be able to use it.

**Comment by EliaSaSe** [comment]
@remilapeyre Ohh, I missed that branch. Thank you for the update. I will build my own plugin from this branch, until the release is available.

**Comment by peimanja** [comment]
I know terraform 0.12.0 just released today but is there any timeline on releasing compatible version?

**Comment by seans11** [comment]
> Hi @EliaSaSe, the work to make this provider work with Terraform 0.12 has been done in the `terraform-0.12` branch (https://github.com/terraform-providers/terraform-provider-consul/tree/terraform-0.12) and it is currently working. The release come shortly.
> 
> In the meantime, it is possible to copy the resulting artifact of `make` to the Terraform plugin folder (https://www.terraform.io/docs/configuration/providers.html#third-party-plugins) and you should be able to use it.

I attempted to compile the latest `terraform-provider-consul` from the terraform 0.12 branch as recommended, but was unable to get it working.

I placed the plugin binary `terraform-provider-consul` in **~/.terraform.d/plugins** and tried to run terraform again, but terraform does not appear to be using it.  I tried specify a `version = "> 2.3.0"` in the consul provider statement, but that didn't correct the problem either.  After running an init and plan I check the provider cache directories (.terraform and ~/.terraform.d/plugin-cache) and no consul provider is found while other providers are there.

The error I'm receiving is:
*Error: Failed to instantiate provider "consul" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]*

Anyone have thoughts on how I might get this working?

**Comment by remilapeyre** [comment]
Hi @seans11 . I don't think you need to specify a versin. Did you ran `terraform init` after adding the binary to to `~/.terraform.d/plugins`?

**Comment by seans11** [comment]
> Hi @seans11 . I don't think you need to specify a versin. Did you ran `terraform init` after adding the binary to to `~/.terraform.d/plugins`?

I did run a `terraform init` and the following was the response I got back:
```terraform
> terraform init
Initializing modules...
- module.base

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.aws: version = "~> 2.12"
* provider.consul: version = "~> 6.0"
* provider.external: version = "~> 1.1"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```
I deleted the entire .terraform directory and started fresh and I can now see the consul provider listed with the other providers, and it shows version 6.0.0 (I named the plugin terraform-provider-consul_v6.0.0_x4 to validate it was seeing the version of consul i compiled).

When I run `terraform providers` using the `version =` statement for my consul provider this is what I get:
```terraform
> terraform providers
.
├── provider.aws
├── provider.consul > 2.3.0
└── module.base
    ├── provider.aws (inherited)
    └── provider.external
```
I did try removing the `version =` argument and I still receive the same error when running `terraform plan`

*Error: Failed to instantiate provider "consul" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]*

**Comment by remilapeyre** [comment]
The version should be `provider.consul (unversioned)`. Did you try to run `rm -rf .terraform && terraform init` when the `version = ` statement was not in the consul provider?

**Comment by seans11** [comment]
> The version should be `provider.consul (unversioned)`. Did you try to run `rm -rf .terraform && terraform init` when the `version = ` statement was not in the consul provider?

I renamed the plugin to `terraform-provider-consul`
I removed the provider statement `version=`
I removed the .terraform directory
I ran `terraform init`

This is what it returned this time:
```terraform
> terraform init
Initializing modules...
- module.base
  Getting source "../global/modules/base"

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.aws: version = "~> 2.12"
* provider.external: version = "~> 1.1"

Terraform has been successfully initialized!
```

Now it doesn't show the consul provider.  Additionally I'm still receiving the "Failed to instantiate provider" error.

**Comment by Lasering** [comment]
If you use the code at the terraform-0.12 branch and change the file `go.mod` to use terraform 0.12 instead of terraform v0.12.0-alpha4.0.20190424121927-9327eedb0417. It works.

So a release should be very easy :wink:

**Comment by remilapeyre** [comment]
Thanks, we are in the process of releasing the bug fixes and new features we had and should do the release for Terraform 0.12 shortly after.

**Comment by remilapeyre** [comment]
The Terraform 0.12 finally happened with the v2.5.0 release :)
